# Generated by Django 4.2.2 on 2023-07-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gappers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.CharField(max_length=255)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('hight', models.FloatField()),
                ('low', models.FloatField()),
                ('vwap', models.FloatField()),
                ('volume', models.FloatField()),
                ('gap', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
