# Generated by Django 4.2.3 on 2023-07-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gappers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('dcount', models.FloatField()),
                ('MA_5', models.FloatField()),
                ('MA_15', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Upperblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('b1_vs', models.FloatField()),
                ('b1_ve', models.FloatField()),
                ('b1_prc', models.FloatField()),
                ('b2_vs', models.FloatField()),
                ('b2_ve', models.FloatField()),
                ('b2_prc', models.FloatField()),
                ('b3_vs', models.FloatField()),
                ('b3_ve', models.FloatField()),
                ('b3_prc', models.FloatField()),
                ('b4_vs', models.FloatField()),
                ('b4_ve', models.FloatField()),
                ('b4_prc', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='gappers',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
